export const MOCK_FEATURES = [
  {
    id: 'mock-1',
    document_id: 'mock-doc',
    feature_id: 'F-01',
    name: 'User Authentication & Role-Based Access Control',
    description: 'Sistem harus menyediakan mekanisme autentikasi multi-faktor (MFA) dengan dukungan SSO. Role-based access control (RBAC) harus mendefinisikan minimal 4 level akses: Super Admin, Admin, Operator, dan Viewer.',
    requirement_classification: 'functional_requirement',
    priority_moscow: 'must_have',
    business_value: 'Menjamin keamanan data dan kepatuhan regulasi. Mengurangi risiko akses tidak sah yang bisa menyebabkan kerugian finansial dan reputasi.',
    capability_gap: 'Saat ini tidak ada kontrol akses berbasis peran — semua user memiliki akses penuh. Ini menyebabkan risiko keamanan tinggi dan tidak bisa memenuhi audit compliance.',
    business_rules: ['Password minimal 12 karakter', 'Sesi tidak aktif 15 menit harus logout otomatis', 'Akun terkunci setelah 5 kali gagal login', '[PERLU VALIDASI] Kebijakan password rotation belum dikonfirmasi dengan tim Security'],
    stakeholders: ['Information Security', 'IT Operations', 'Compliance Officer', 'End Users (potensi resistensi terhadap MFA)'],
    preconditions: 'User telah terdaftar di sistem HR dan memiliki email korporat aktif.',
    postconditions: 'User berhasil login dan mendapatkan akses sesuai peran yang ditetapkan.',
    acceptance_criteria: ['Login berhasil dan menghasilkan session yang valid', 'MFA berfungsi dan wajib untuk role Admin ke atas', 'RBAC membatasi akses menu dan data sesuai role', 'Audit log mencatat semua aktivitas login'],
    dependencies_and_risks: 'Bergantung pada keputusan Identity Provider yang belum dipilih. Risiko: adopsi MFA oleh end user bisa lambat jika tidak ada change management yang memadai.',
    accounting_impact: 'Tidak ada',
  },
  {
    id: 'mock-2',
    document_id: 'mock-doc',
    feature_id: 'F-02',
    name: 'Real-time Document Collaboration',
    description: 'Platform harus mendukung kolaborasi real-time pada dokumen BRD di mana multiple user dapat mengedit, memberikan komentar, dan melacak revisi secara simultan.',
    requirement_classification: 'functional_requirement',
    priority_moscow: 'must_have',
    business_value: 'Mengurangi siklus review dokumen dari rata-rata 5 hari menjadi 1 hari. Menghilangkan konflik versi dokumen yang sering menyebabkan rework.',
    capability_gap: 'Proses review saat ini dilakukan via email dengan attachment. Tidak ada versioning, sering terjadi konflik dokumen, dan tidak ada audit trail siapa mengubah apa.',
    business_rules: ['Hanya satu user yang bisa mengedit bagian yang sama dalam satu waktu', 'Setiap revisi harus tercatat dengan timestamp dan identitas user', '[PERLU VALIDASI] Kebijakan retensi dokumen belum dikonfirmasi'],
    stakeholders: ['Business Analyst', 'Project Manager', 'Technical Lead', 'Tim Legal (terdampak perubahan proses review kontrak)'],
    preconditions: 'User sudah memiliki akun dan dokumen sudah dibuat di platform.',
    postconditions: 'Semua perubahan tersimpan real-time dan semua kontributor melihat versi terkini.',
    acceptance_criteria: ['Perubahan dari satu user terlihat oleh user lain dalam 2 detik', 'Conflict resolution berjalan otomatis tanpa kehilangan data', 'History revisi lengkap tersedia dan bisa di-restore'],
    dependencies_and_risks: 'Bergantung pada F-01 (autentikasi). Risiko: user yang terbiasa email-based workflow bisa resisten terhadap perubahan proses ini.',
    accounting_impact: 'Tidak ada',
  },
  {
    id: 'mock-3',
    document_id: 'mock-doc',
    feature_id: 'F-03',
    name: 'Keamanan Data & Enkripsi End-to-End',
    description: 'Semua data sensitif harus dienkripsi at-rest dan in-transit. Platform harus memenuhi standar keamanan enterprise dan regulasi yang berlaku.',
    requirement_classification: 'non_functional_requirement',
    priority_moscow: 'must_have',
    business_value: 'Memenuhi kewajiban regulasi dan melindungi data sensitif perusahaan dari breach. Mencegah potensi denda dan kerusakan reputasi.',
    capability_gap: 'Saat ini tidak ada enkripsi at-rest. Data tersimpan dalam format plain text yang rentan jika terjadi akses tidak sah ke database.',
    business_rules: ['Enkripsi AES-256 untuk data at-rest', 'TLS 1.3 untuk semua komunikasi', 'Kunci enkripsi harus dirotasi setiap 90 hari', '[PERLU VALIDASI] Standar keamanan spesifik industri yang berlaku belum dikonfirmasi'],
    stakeholders: ['CISO', 'Compliance Officer', 'IT Security', 'Data Privacy Officer'],
    preconditions: 'Key management system sudah tersedia atau keputusan vendor sudah dibuat.',
    postconditions: 'Semua data sensitif terenkripsi dan sistem lolos security audit.',
    acceptance_criteria: ['Penetration test tidak menemukan data sensitif dalam plain text', 'Enkripsi in-transit terverifikasi via SSL checker', 'Key rotation berjalan otomatis tanpa downtime'],
    dependencies_and_risks: 'Bergantung pada keputusan key management solution. Risiko: jika kunci enkripsi hilang, data tidak bisa dipulihkan.',
    accounting_impact: 'Tidak ada',
  },
];

export const MOCK_DISCOVERY_QUESTIONS = [
  {
    question: 'Siapa yang secara resmi bertanggung jawab atas keberhasilan inisiatif ini dari sisi bisnis, dan bagaimana mereka akan diukur performanya terkait proyek ini?',
    context: 'Tanpa business owner yang jelas dan akuntabel, keputusan akan lambat dan tidak ada yang bertanggung jawab jika proyek gagal memberikan nilai.',
    category: 'ownership_accountability',
    target_stakeholder: 'Project Sponsor / Direktur',
    priority: 'high',
    urgency: 'ask_now',
  },
  {
    question: 'Apa definisi sukses yang spesifik dan terukur untuk inisiatif ini dalam 6 bulan pertama setelah go-live, dan siapa yang akan mengukurnya?',
    context: 'BRD tidak mendefinisikan metrik keberhasilan bisnis yang konkret. Tanpa ini, tidak ada cara untuk menilai apakah investasi ini worthwhile.',
    category: 'business_case',
    target_stakeholder: 'Business Owner / Product Manager',
    priority: 'high',
    urgency: 'ask_now',
  },
  {
    question: 'Berapa total biaya yang diproyeksikan (termasuk biaya lisensi, implementasi, training, dan change management) dan bagaimana ROI-nya dihitung?',
    context: 'BRD tidak mencantumkan justifikasi finansial. Tanpa business case yang solid, sulit mempertahankan anggaran ini di hadapan manajemen.',
    category: 'business_case',
    target_stakeholder: 'Project Sponsor / Finance',
    priority: 'high',
    urgency: 'ask_before_kickoff',
  },
  {
    question: 'Bagaimana proses bisnis yang ada sekarang akan berubah, dan siapa yang sudah dikonsultasikan dari tim operasional yang akan terdampak langsung?',
    context: 'Change management yang buruk adalah penyebab utama kegagalan adopsi sistem baru. Tim yang terdampak perlu dilibatkan sejak awal.',
    category: 'change_readiness',
    target_stakeholder: 'Operations Manager / Change Manager',
    priority: 'high',
    urgency: 'ask_before_kickoff',
  },
  {
    question: 'Apa rencana rollback jika sistem baru gagal atau adopsi pengguna jauh di bawah target setelah 3 bulan go-live?',
    context: 'BRD tidak mendefinisikan exit strategy atau rollback plan. Tanpa ini, organisasi terjebak tanpa opsi jika implementasi bermasalah.',
    category: 'rollback_plan',
    target_stakeholder: 'IT Manager / Project Manager',
    priority: 'high',
    urgency: 'ask_before_sign_off',
  },
  {
    question: 'Bagaimana sistem ini akan terintegrasi dengan sistem yang sudah ada, dan apakah vendor/tim sistem tersebut sudah dikonfirmasi kesediaannya untuk berkolaborasi?',
    context: 'Integrasi yang tidak divalidasi ke sistem existing adalah risiko terbesar yang sering menyebabkan delay dan cost overrun.',
    category: 'integration',
    target_stakeholder: 'IT Architecture / Vendor Manager',
    priority: 'high',
    urgency: 'ask_now',
  },
  {
    question: 'Apa yang terjadi pada data historis yang ada saat ini, dan bagaimana keputusan migrasi data dibuat serta siapa yang bertanggung jawab atas kualitas data migrasi?',
    context: 'Data migration yang buruk bisa menyebabkan operasional terganggu selama berbulan-bulan. Ini sering diremehkan di fase perencanaan.',
    category: 'data_integrity',
    target_stakeholder: 'Data Owner / IT Manager',
    priority: 'high',
    urgency: 'ask_before_kickoff',
  },
  {
    question: 'Apakah ada regulasi, kebijakan internal, atau komitmen kontraktual yang membatasi bagaimana data dalam sistem ini bisa disimpan, diakses, atau dihapus?',
    context: 'Compliance yang tidak diidentifikasi di awal bisa memaksa rework besar di tengah implementasi atau bahkan membatalkan proyek.',
    category: 'business_rule',
    target_stakeholder: 'Compliance Officer / Legal',
    priority: 'high',
    urgency: 'ask_now',
  },
  {
    question: 'Bagaimana sistem ini akan menangani situasi di mana data input tidak lengkap, tidak valid, atau konflik dengan data di sistem lain?',
    context: 'Edge case data sering tidak dipikirkan di BRD tapi menjadi masalah operasional terbesar setelah go-live.',
    category: 'edge_case',
    target_stakeholder: 'Business Analyst / Operations',
    priority: 'medium',
    urgency: 'ask_before_sign_off',
  },
  {
    question: 'Apakah semua stakeholder kunci sudah setuju dengan scope yang didefinisikan, dan siapa yang memiliki otoritas untuk menyetujui perubahan scope selama proyek berjalan?',
    context: 'Scope creep yang tidak terkontrol adalah penyebab utama proyek melebihi budget dan timeline.',
    category: 'scope',
    target_stakeholder: 'Project Sponsor / Steering Committee',
    priority: 'high',
    urgency: 'ask_now',
  },
  {
    question: 'Bagaimana tim akan memastikan bahwa pengguna akhir benar-benar mengadopsi sistem baru ini, dan apa rencana training serta komunikasi yang sudah disiapkan?',
    context: 'Sistem terbaik pun tidak akan memberikan nilai jika pengguna kembali ke cara lama. Adoption plan harus ada sebelum kickoff.',
    category: 'change_readiness',
    target_stakeholder: 'HR / Training Manager / Change Manager',
    priority: 'high',
    urgency: 'ask_before_kickoff',
  },
  {
    question: 'Kriteria apa yang akan digunakan untuk UAT, siapa yang berwenang memberikan sign-off, dan apa konsekuensinya jika UAT gagal di tanggal yang sudah dijadwalkan?',
    category: 'acceptance_criteria',
    context: 'UAT yang tidak terdefinisi dengan jelas sering menyebabkan konflik antara IT dan bisnis saat menentukan apakah sistem siap go-live.',
    target_stakeholder: 'Business Owner / QA Lead',
    priority: 'medium',
    urgency: 'ask_before_sign_off',
  },
];

export const MOCK_RISKS = [
  {
    risk_event: 'Adopsi pengguna jauh di bawah target akibat kurangnya change management dan training yang memadai',
    impact: 'high',
    likelihood: 'likely',
    business_impact: 'Sistem yang tidak diadopsi berarti investasi tidak menghasilkan ROI. Estimasi kerugian: 100% biaya implementasi terbuang jika adopsi di bawah 40% dalam 6 bulan.',
    mitigation_strategy: 'Bentuk Change Management team dengan representasi dari unit bisnis. Lakukan roadshow dan training sebelum go-live. Tetapkan adoption KPI yang dimonitor mingguan.',
    risk_owner: 'HR Manager / Change Management Lead',
  },
  {
    risk_event: 'Ketergantungan pada vendor atau sistem eksternal yang tidak terkontrol menyebabkan delay implementasi',
    impact: 'high',
    likelihood: 'possible',
    business_impact: 'Setiap bulan delay berarti biaya operasional existing system terus berjalan. Estimasi: keterlambatan 3 bulan bisa meningkatkan total proyek cost hingga 25%.',
    mitigation_strategy: 'Konfirmasi komitmen vendor secara tertulis dengan SLA. Identifikasi dependensi kritis dan buat contingency plan untuk setiap dependensi eksternal.',
    risk_owner: 'Project Manager / Vendor Manager',
  },
  {
    risk_event: 'Scope creep yang tidak terkontrol menyebabkan proyek melebihi budget dan timeline',
    impact: 'critical',
    likelihood: 'likely',
    business_impact: 'Berdasarkan data historis proyek IT, scope creep rata-rata menambah 40-60% biaya awal. Ini bisa menyebabkan proyek di-cancel atau mengorbankan fitur kritikal.',
    mitigation_strategy: 'Terapkan formal change control process. Setiap permintaan perubahan scope harus melalui impact assessment dan disetujui Project Sponsor. Review scope setiap 2 minggu.',
    risk_owner: 'Project Sponsor / Steering Committee',
  },
  {
    risk_event: 'Data migration dari sistem lama tidak akurat atau tidak lengkap, mengganggu operasional bisnis',
    impact: 'critical',
    likelihood: 'possible',
    business_impact: 'Data yang salah dalam sistem baru bisa menyebabkan keputusan bisnis yang salah, compliance issue, dan hilangnya kepercayaan pengguna. Remediation bisa memakan waktu berbulan-bulan.',
    mitigation_strategy: 'Lakukan data audit dan cleansing sebelum migrasi. Tetapkan Data Quality Gate yang harus dipenuhi sebelum go-live. Pertahankan akses ke sistem lama selama 90 hari sebagai fallback.',
    risk_owner: 'Data Owner / IT Manager',
  },
  {
    risk_event: 'Ketidakselarasan antara ekspektasi bisnis dan kemampuan sistem yang dibangun menyebabkan konflik saat UAT',
    impact: 'high',
    likelihood: 'possible',
    business_impact: 'Konflik di UAT bisa menunda go-live 1-3 bulan dan memaksa rework yang mahal. Ini juga merusak kepercayaan antara IT dan bisnis untuk proyek-proyek berikutnya.',
    mitigation_strategy: 'Lakukan business walkthrough setelah setiap sprint. Libatkan business representative dalam review kemajuan mingguan. Dokumentasikan semua keputusan desain dengan sign-off bisnis.',
    risk_owner: 'Business Owner / Product Manager',
  },
];

export const MOCK_IMPROVEMENTS = [
  {
    title: 'Tidak Ada Business Owner yang Terdefinisi',
    description: 'BRD tidak mencantumkan siapa yang bertanggung jawab atas keberhasilan bisnis dari inisiatif ini. Tanpa business owner yang jelas, keputusan akan lambat, eskalasi tidak ada yang menerima, dan tidak ada yang bertanggung jawab jika proyek gagal memberikan nilai. Ini adalah gap paling kritis yang harus diselesaikan sebelum proyek bisa dilanjutkan.',
    category: 'missing_owner',
    priority: 'high',
  },
  {
    title: 'Metrik Keberhasilan Bisnis Tidak Terdefinisi',
    description: 'BRD mendefinisikan fitur dan requirement teknis, tetapi tidak mendefinisikan bagaimana kesuksesan bisnis akan diukur. Tidak ada KPI, target angka, atau timeline pengukuran. Tanpa ini, tidak ada cara objektif untuk menilai apakah investasi ini worth it, dan tidak ada dasar untuk keputusan go/no-go setelah implementasi.',
    category: 'undefined_success_metric',
    priority: 'high',
  },
  {
    title: 'Scope Tidak Dibatasi dengan Jelas',
    description: 'Beberapa requirement menggunakan bahasa yang ambigu seperti "dan fitur terkait lainnya" atau "sesuai kebutuhan". Formulasi seperti ini membuka pintu untuk scope creep yang tidak terkontrol. Setiap requirement harus memiliki batas yang jelas tentang apa yang termasuk dan tidak termasuk.',
    category: 'scope_not_bounded',
    priority: 'high',
  },
  {
    title: 'Rencana Change Management Tidak Ada',
    description: 'BRD fokus pada apa yang akan dibangun tetapi tidak membahas bagaimana perubahan ini akan diadopsi oleh pengguna. Tidak ada rencana training, komunikasi, atau transition support. Ini adalah penyebab utama kegagalan adopsi sistem baru di organisasi enterprise.',
    category: 'change_impact_ignored',
    priority: 'high',
  },
  {
    title: 'Dependensi Kritis Tidak Dikonfirmasi',
    description: 'BRD menyebutkan beberapa integrasi dengan sistem eksternal tetapi tidak mengkonfirmasi apakah pihak-pihak terkait sudah setuju dan memiliki kapasitas untuk berkolaborasi. Asumsi bahwa sistem lain siap untuk diintegrasikan tanpa konfirmasi adalah risiko schedule yang sangat tinggi.',
    category: 'missing_dependency',
    priority: 'high',
  },
  {
    title: 'Implikasi Regulasi dan Compliance Belum Dianalisis',
    description: 'BRD tidak secara eksplisit menganalisis regulasi apa yang berlaku untuk sistem ini dan bagaimana compliance-nya akan dipenuhi dan dibuktikan. Compliance yang tidak diidentifikasi di awal bisa memaksa rework besar atau bahkan menghentikan proyek.',
    category: 'compliance_not_addressed',
    priority: 'medium',
  },
];

export const MOCK_ENABLEMENT = [
  {
    feature_id: 'F-01',
    feature_name: 'User Authentication & RBAC',
    business_owner: 'Head of IT Security / CISO',
    change_impact: 'Semua pengguna harus beradaptasi dengan proses login baru termasuk MFA. Admin perlu mempelajari cara mengelola role dan permission. Tim IT Security mendapatkan tanggung jawab baru untuk mengelola identitas dan akses.',
    readiness_assessment: 'partially_ready',
    readiness_notes: 'Tim Security sudah ada dan memahami konsep RBAC, tetapi belum ada SOP untuk onboarding/offboarding pengguna dengan sistem baru ini. Decision on Identity Provider belum dibuat.',
    enablement_actions: [
      'Finalisasi pilihan Identity Provider dengan tim IT Security',
      'Buat dan validasi SOP onboarding/offboarding pengguna',
      'Siapkan modul training MFA untuk semua pengguna (estimasi 2 jam)',
      'Komunikasikan perubahan login process minimal 4 minggu sebelum go-live',
      'Siapkan helpdesk FAQ untuk pertanyaan umum terkait MFA',
    ],
    success_metric: 'Tingkat adopsi MFA mencapai 95% dalam 30 hari setelah go-live. Zero security incident terkait akses tidak sah dalam 6 bulan pertama.',
    change_complexity: 'high',
  },
  {
    feature_id: 'F-02',
    feature_name: 'Real-time Document Collaboration',
    business_owner: 'Head of Business Analysis / PMO',
    change_impact: 'Tim BA dan PM harus meninggalkan kebiasaan review via email dan beralih ke platform kolaborasi. Proses approval dokumen berubah secara fundamental. Tim Legal perlu menyesuaikan cara mereka me-review dan sign-off dokumen.',
    readiness_assessment: 'not_ready',
    readiness_notes: 'Belum ada assessment seberapa kuat resistensi dari tim yang sudah sangat terbiasa dengan email-based workflow. Tim Legal khususnya belum dikonsultasikan sama sekali tentang perubahan proses review mereka.',
    enablement_actions: [
      'Lakukan workshop dengan tim BA, PM, dan Legal untuk memahami pain point proses saat ini',
      'Buat perbandingan before/after workflow yang jelas untuk setiap tim',
      'Pilih dan latih internal champions dari setiap tim sebelum rollout luas',
      'Tetapkan tanggal sunset untuk proses review via email secara resmi',
      'Siapkan template dokumen standar di platform baru',
    ],
    success_metric: 'Waktu rata-rata siklus review dokumen turun dari 5 hari menjadi maksimal 1 hari dalam 60 hari setelah go-live. Penggunaan email untuk review dokumen turun 80%.',
    change_complexity: 'high',
  },
  {
    feature_id: 'F-03',
    feature_name: 'Keamanan Data & Enkripsi',
    business_owner: 'CISO / Data Privacy Officer',
    change_impact: 'Perubahan ini mayoritas transparan bagi pengguna akhir, tetapi tim IT Operations perlu memahami prosedur key management yang baru. Tim Compliance mendapat tanggung jawab baru untuk memverifikasi enkripsi dalam audit.',
    readiness_assessment: 'partially_ready',
    readiness_notes: 'Tim Security memiliki kompetensi dasar, tetapi belum ada SOP untuk key rotation dan incident response jika terjadi key compromise. Standar regulasi spesifik yang harus dipenuhi belum dikonfirmasi.',
    enablement_actions: [
      'Konfirmasi standar regulasi yang berlaku dengan Compliance Officer',
      'Buat SOP key management termasuk prosedur rotasi dan recovery',
      'Training tim IT Operations tentang prosedur enkripsi dan key management',
      'Jadwalkan security audit eksternal sebelum go-live',
    ],
    success_metric: 'Sistem lolos security audit eksternal tanpa temuan kritikal. Zero data breach incident dalam 12 bulan pertama operasional.',
    change_complexity: 'medium',
  },
];

export const MOCK_STRATEGIC_ALIGNMENT = [
  {
    title: 'ROI Inisiatif Tidak Terdokumentasi',
    description: 'BRD tidak menyertakan business case atau kalkulasi ROI. Tidak ada perbandingan biaya implementasi vs manfaat bisnis yang terukur. Tanpa justifikasi finansial yang jelas, sulit mempertahankan anggaran ini di hadapan dewan direksi atau saat terjadi tekanan pemotongan biaya.',
    category: 'roi_unclear',
    priority: 'high',
    impact: 'Tanpa ROI yang jelas, proyek rentan dibatalkan atau dikurangi anggarannya di tengah jalan, membuang semua investasi yang sudah dikeluarkan.',
    recommended_action: 'Minta Business Owner membuat business case satu halaman dengan proyeksi ROI dalam 12, 24, dan 36 bulan sebelum dokumen ini bisa di-sign off.',
  },
  {
    title: 'Risiko Scope Creep Sangat Tinggi',
    description: 'Beberapa requirement menggunakan formulasi terbuka yang mengundang interpretasi berbeda-beda. Tanpa mekanisme formal change control, setiap "keinginan tambahan" dari stakeholder bisa masuk ke dalam scope tanpa dampak terukur pada timeline dan budget.',
    category: 'scope_creep_risk',
    priority: 'high',
    impact: 'Scope creep rata-rata menambah 40-60% biaya proyek IT enterprise. Jika tidak dikendalikan sejak awal, proyek ini berpotensi melebihi budget secara signifikan.',
    recommended_action: 'Tetapkan formal Change Control Board sebelum kickoff. Setiap perubahan scope wajib melalui impact assessment tertulis dan disetujui Project Sponsor.',
  },
  {
    title: 'Kesiapan Organisasi untuk Perubahan Belum Dinilai',
    description: 'BRD mengasumsikan bahwa organisasi siap menerima perubahan ini tanpa melakukan Organizational Readiness Assessment. Proyek ini melibatkan perubahan cara kerja yang signifikan di beberapa unit bisnis, tetapi tidak ada rencana untuk mengelola transisi.',
    category: 'change_fatigue_risk',
    priority: 'high',
    impact: 'Kegagalan adopsi bisa membuat inisiatif ini tidak memberikan nilai bisnis meskipun sistem berfungsi secara teknis — skenario terburuk: sistem dibangun tapi tidak digunakan.',
    recommended_action: 'Lakukan Organizational Readiness Assessment sebelum kickoff. Jika ada proyek besar lain yang sedang berjalan, pertimbangkan phasing untuk menghindari change fatigue.',
  },
  {
    title: 'Keselarasan dengan Strategi IT Jangka Panjang Perlu Dikonfirmasi',
    description: 'Tidak ada referensi ke IT roadmap atau enterprise architecture yang berlaku. Keputusan teknologi yang dibuat dalam proyek ini bisa konflik dengan arah strategis IT jangka panjang, menyebabkan technical debt atau keharusan migrasi ulang di kemudian hari.',
    category: 'strategic_misalignment',
    priority: 'medium',
    impact: 'Investasi dalam teknologi yang tidak selaras dengan roadmap IT bisa menjadi beban jangka panjang yang membutuhkan re-platform 2-3 tahun ke depan.',
    recommended_action: 'Review dokumen ini bersama Enterprise Architect untuk mengkonfirmasi keselarasan dengan IT roadmap dan enterprise architecture principles.',
  },
  {
    title: 'Governance dan Pengambilan Keputusan Selama Proyek Tidak Terdefinisi',
    description: 'BRD tidak mendefinisikan struktur governance proyek: siapa yang bisa membuat keputusan apa, bagaimana eskalasi dilakukan, dan siapa yang memiliki veto power. Tanpa ini, keputusan kritis akan terhambat atau dibuat oleh orang yang salah.',
    category: 'governance_gap',
    priority: 'medium',
    impact: 'Governance yang buruk adalah penyebab utama proyek terlambat mengambil keputusan kritis, yang berakibat pada delay dan cost overrun.',
    recommended_action: 'Definisikan RACI matrix untuk keputusan-keputusan kunci proyek. Bentuk Steering Committee dengan jadwal review berkala minimal sebulan sekali.',
  },
];

export const MOCK_ADVISORY = MOCK_STRATEGIC_ALIGNMENT;
export const MOCK_OPTIMIZATIONS = MOCK_IMPROVEMENTS;
export const MOCK_SOLUTIONS = MOCK_ENABLEMENT;
