export const MOCK_FEATURES = [
  {
    id: 'mock-1',
    document_id: 'mock-doc',
    feature_id: 'F-01',
    name: 'User Authentication & Role-Based Access Control',
    description: 'Sistem harus menyediakan mekanisme autentikasi multi-faktor (MFA) dengan dukungan SSO melalui SAML 2.0 dan OAuth 2.0. Role-based access control (RBAC) harus mendefinisikan minimal 4 level akses: Super Admin, Admin, Operator, dan Viewer.',
    requirement_classification: 'functional_requirement',
    priority_moscow: 'must_have',
    business_value: 'Menjamin keamanan data dan kepatuhan terhadap regulasi ISO 27001 serta memungkinkan audit trail per pengguna.',
    capability_gap: 'Saat ini menggunakan autentikasi basic. Tidak ada mekanisme RBAC atau audit logging.',
    business_rules: ['Password minimal 12 karakter dengan kombinasi huruf, angka, dan simbol', 'Sesi tidak aktif selama 15 menit harus logout otomatis', 'Akun terkunci setelah 5 kali gagal login dalam 30 menit'],
    stakeholders: ['Information Security', 'IT Operations', 'Compliance Officer'],
    preconditions: 'User telah terdaftar di sistem HRIS dan memiliki email korporat aktif.',
    postconditions: 'User berhasil login dan mendapatkan token akses dengan hak akses sesuai role.',
    acceptance_criteria: ['Login dengan username/password berhasil', 'MFA via Google Authenticator berfungsi', 'SSO dengan SAML 2.0 berhasil', 'RBAC membatasi akses sesuai role'],
    dependencies_and_risks: 'Bergantung pada implementasi SAML Identity Provider yang sudah ada. Risiko: kompleksitas integrasi SSO dengan legacy system.',
    accounting_impact: 'Tidak ada',
  },
  {
    id: 'mock-2',
    document_id: 'mock-doc',
    feature_id: 'F-02',
    name: 'Real-time Document Collaboration',
    description: 'Platform harus mendukung kolaborasi real-time pada dokumen BRD dimana multiple user dapat mengedit, memberikan komentar, dan melacak revisi secara simultan dengan conflict resolution.',
    requirement_classification: 'functional_requirement',
    priority_moscow: 'must_have',
    business_value: 'Mengurangi siklus review dokumen dari rata-rata 5 hari menjadi 1 hari melalui kolaborasi sinkron.',
    capability_gap: 'Proses review saat ini dilakukan via email dengan attachment. Tidak ada versioning atau real-time sync.',
    business_rules: ['Hanya satu user yang dapat mengedit paragraf yang sama dalam satu waktu', 'Setiap revisi harus tercatat dengan timestamp dan user ID', 'Conflict resolution menggunakan last-write-wins dengan notifikasi'],
    stakeholders: ['Business Analyst', 'Project Manager', 'Technical Writer'],
    preconditions: 'Dokumen telah dibuat dan user memiliki akses edit.',
    postconditions: 'Semua perubahan tersimpan secara real-time dengan history lengkap.',
    acceptance_criteria: ['Dua user dapat mengedit dokumen berbeda secara simultan', 'Kommentar muncul real-time tanpa refresh', 'Conflict resolution berjalan otomatis', 'Riwayat revisi dapat dilihat per detik'],
    dependencies_and_risks: 'Membutuhkan WebSocket infrastructure. Risiko: latency pada koneksi internet lambat.',
    accounting_impact: 'Tidak ada',
  },
  {
    id: 'mock-3',
    document_id: 'mock-doc',
    feature_id: 'F-03',
    name: 'AI-Powered Requirement Extraction & Classification',
    description: 'Sistem harus mampu mengekstrak requirement secara otomatis dari dokumen BRD menggunakan NLP, mengklasifikasikannya ke dalam kategori (Fungsional, Non-Fungsional, Business Rules), dan menyarankan prioritas MoSCoW.',
    requirement_classification: 'functional_requirement',
    priority_moscow: 'should_have',
    business_value: 'Mengurangi waktu ekstraksi manual dari 3 hari menjadi 30 menit dengan akurasi >85%.',
    capability_gap: 'Ekstraksi requirement saat ini dilakukan manual oleh senior BA. Tidak ada AI-assisted analysis.',
    business_rules: ['Hasil ekstraksi harus melalui review manusia sebelum disetujui', 'Confidence score di bawah 70% harus ditandai untuk review manual', 'Klasifikasi harus mapping ke BABOK v3 taxonomy'],
    stakeholders: ['Business Analyst', 'Solution Architect', 'QA Lead'],
    preconditions: 'Dokumen BRD telah diupload dalam format PDF atau DOCX.',
    postconditions: 'Requirements terekstrak, terklasifikasi, dan tersimpan di database dengan confidence score.',
    acceptance_criteria: ['Ekstraksi dari dokumen 50 halaman selesai <5 menit', 'Klasifikasi requirement akurat >85%', 'Prioritas MoSCoW sesuai dengan business value'],
    dependencies_and_risks: 'Membutuhkan akses ke LLM API (DeepSeek/GPT). Risiko: biaya API dan akurasi pada dokumen berkualitas rendah.',
    accounting_impact: 'Dicatat sebagai biaya operasional untuk AI processing.',
  },
  {
    id: 'mock-4',
    document_id: 'mock-doc',
    feature_id: 'F-04',
    name: 'Dashboard & Reporting Analytics',
    description: 'Dashboard eksekutif yang menampilkan KPI proyek secara real-time termasuk health score, milestone tracking, burndown chart, dan resource utilization metrics.',
    requirement_classification: 'functional_requirement',
    priority_moscow: 'should_have',
    business_value: 'Memberikan visibilitas real-time ke management untuk pengambilan keputusan cepat dan proaktif.',
    capability_gap: 'Reporting saat ini dilakukan manual setiap minggu via spreadsheet. Tidak ada real-time dashboard.',
    business_rules: ['Data dashboard harus real-time dengan maksimal latency 5 detik', 'Ekspor laporan dalam format PDF dan Excel', 'Filter berdasarkan periode, project, dan stakeholder'],
    stakeholders: ['Project Management Office', 'C-Level', 'Delivery Lead'],
    preconditions: 'Data project telah dikonfigurasi dan diintegrasikan.',
    postconditions: 'Dashboard menampilkan data terkini dengan visualisasi interaktif.',
    acceptance_criteria: ['Dashboard load <3 detik', 'Filter berfungsi dengan benar', 'Ekspor PDF menghasilkan laporan yang rapi'],
    dependencies_and_risks: 'Membutuhkan data warehouse integration. Risiko: performa query pada dataset besar.',
    accounting_impact: 'Tidak ada',
  },
  {
    id: 'mock-5',
    document_id: 'mock-doc',
    feature_id: 'F-05',
    name: 'Automated Notification & Alert Engine',
    description: 'Sistem notifikasi multi-channel (email, in-app, Slack) untuk alert milestone, task assignment, deadline reminders, dan anomaly detection dengan escalation matrix.',
    requirement_classification: 'functional_requirement',
    priority_moscow: 'could_have',
    business_value: 'Mengurangi missed deadline sebesar 90% melalui notifikasi proaktif dan eskalasi otomatis.',
    capability_gap: 'Notifikasi saat ini hanya via email manual. Tidak ada alert otomatis atau integrasi Slack.',
    business_rules: ['Notifikasi prioritas tinggi harus terkirim dalam <1 menit', 'Eskalasi otomatis jika tidak ada action dalam 24 jam', 'User dapat mengatur preferensi notifikasi per channel'],
    stakeholders: ['Project Manager', 'Team Lead', 'All Users'],
    preconditions: 'Event trigger telah terdefinisi (task overdue, milestone tercapai, dll).',
    postconditions: 'Notifikasi terkirim ke channel yang sesuai dengan template yang telah ditentukan.',
    acceptance_criteria: ['Email notifikasi terkirim <1 menit setelah event', 'Slack webhook berfungsi', 'User preferences dihormati'],
    dependencies_and_risks: 'Membutuhkan Slack API dan SMTP server. Risiko: rate limiting pada Slack API.',
    accounting_impact: 'Tidak ada',
  },
  {
    id: 'mock-6',
    document_id: 'mock-doc',
    feature_id: 'NF-01',
    name: 'System Performance & Scalability Requirements',
    description: 'Sistem harus mendukung 10,000 user concurrent dengan response time <500ms untuk 95% requests, dan throughput minimal 1,000 transaksi per detik pada peak hours.',
    requirement_classification: 'non_functional_requirement',
    priority_moscow: 'must_have',
    business_value: 'Menjamin user experience yang responsif dan kemampuan scaling seiring pertumbuhan bisnis.',
    capability_gap: 'Sistem saat ini hanya mendukung 500 user concurrent dengan response time 2-3 detik.',
    business_rules: ['Query database >3 detik harus dioptimasi', 'Caching layer untuk data statis minimal TTL 5 menit', 'Auto-scaling trigger di 70% resource utilization'],
    stakeholders: ['Infrastructure Team', 'DevOps', 'Architecture Board'],
    preconditions: 'Infrastructure telah diprovisioning dengan auto-scaling group.',
    postconditions: 'Sistem berjalan dengan metrik performa yang sesuai SLA.',
    acceptance_criteria: ['Load test 10,000 user concurrent', 'Response time <500ms untuk 95% requests', 'Throughput 1,000 TPS terpenuhi'],
    dependencies_and_risks: 'Membutuhkan cloud infrastructure dengan auto-scaling. Risiko: biaya infrastruktur tinggi.',
    accounting_impact: 'Dicatat sebagai biaya operasional infrastruktur cloud.',
  },
  {
    id: 'mock-7',
    document_id: 'mock-doc',
    feature_id: 'NF-02',
    name: 'Security & Compliance Requirements',
    description: 'Sistem harus memenuhi standar keamanan ISO 27001, PCI DSS (jika memproses pembayaran), dan GDPR untuk perlindungan data pengguna di Uni Eropa.',
    requirement_classification: 'non_functional_requirement',
    priority_moscow: 'must_have',
    business_value: 'Kepatuhan regulasi menghindari denda hingga 4% dari revenue global (GDPR) dan membuka pasar enterprise.',
    capability_gap: 'Sistem saat ini belum memiliki sertifikasi keamanan formal dan tidak memiliki data residency controls.',
    business_rules: ['Data pengguna Eropa harus disimpan di server EU', 'Enkripsi data at-rest AES-256', 'Enkripsi data in-transit TLS 1.3', 'Audit logging untuk semua akses data sensitif'],
    stakeholders: ['DPO', 'Legal & Compliance', 'Security Team'],
    preconditions: 'Security baseline telah ditetapkan dan disetujui.',
    postconditions: 'Sistem memenuhi persyaratan audit keamanan.',
    acceptance_criteria: ['Penetration testing lulus tanpa critical finding', 'Data residency compliance terverifikasi', 'Encryption standard terpenuhi'],
    dependencies_and_risks: 'Membutuhkan Data Protection Officer review. Risiko: perubahan regulasi yang dinamis.',
    accounting_impact: 'Dicatat sebagai biaya kepatuhan dan audit tahunan.',
  },
];

export const MOCK_DISCOVERY_QUESTIONS = [
  {
    question: 'Bagaimana skenario rollback jika implementasi SSO gagal? Apakah ada fallback ke autentikasi existing?',
    context: 'Integrasi SSO adalah critical path. Tanpa rollback plan yang jelas, migrasi bisa terhambat.',
    category: 'integration',
    target_stakeholder: 'IT Security Lead',
    priority: 'high',
  },
  {
    question: 'Apa kriteria spesifik untuk "real-time" pada kolaborasi dokumen? Apakah sub-second latency acceptable?',
    context: 'Definisi real-time perlu disepakati karena mempengaruhi pilihan teknologi WebSocket vs polling.',
    category: 'acceptance_criteria',
    target_stakeholder: 'Solution Architect',
    priority: 'high',
  },
  {
    question: 'Siapa yang bertanggung jawab melakukan review hasil ekstraksi AI sebelum requirements masuk ke database?',
    context: 'AI confidence score tidak 100%. Perlu jelas SLA review manusia untuk menjaga kualitas data.',
    category: 'business_rule',
    target_stakeholder: 'QA Lead',
    priority: 'medium',
  },
  {
    question: 'Apakah dashboard reporting perlu mendukung real-time atau near-real-time (5 menit delay)?',
    context: 'Real-time membutuhkan infrastruktur streaming yang lebih kompleks dan mahal.',
    category: 'scope',
    target_stakeholder: 'Project Manager',
    priority: 'medium',
  },
  {
    question: 'Format notifikasi apa saja yang diperlukan selain email dan Slack? Apakah SMS atau WhatsApp diperlukan untuk critical alert?',
    context: 'Menentukan channel notifikasi yang tepat menghindari over-engineering dan biaya integrasi yang tidak perlu.',
    category: 'scope',
    target_stakeholder: 'Product Owner',
    priority: 'low',
  },
  {
    question: 'Apakah ada data legacy yang perlu dimigrasi? Berapa estimasi volume data dan formatnya?',
    context: 'Data migration adalah salah satu risiko terbesar dalam implementasi sistem baru. Perlu assessment data existing.',
    category: 'data_mapping',
    target_stakeholder: 'Data Steward',
    priority: 'high',
  },
  {
    question: 'Bagaimana handling concurrent edit conflict pada paragraf yang sama? Apakah last-write-wins acceptable atau perlu mekanisme merge?',
    context: 'Conflict resolution strategy mempengaruhi UX secara signifikan. Last-write-wins bisa menyebabkan data loss.',
    category: 'edge_case',
    target_stakeholder: 'UX Designer',
    priority: 'medium',
  },
  {
    question: 'Apakah ada persyaratan aksesibilitas (WCAG) yang harus dipenuhi? Level AA atau AAA?',
    context: 'Aksesibilitas mempengaruhi desain UI dan komponen secara fundamental. Perlu ditentukan sejak awal.',
    category: 'scope',
    target_stakeholder: 'Accessibility Lead',
    priority: 'medium',
  },
];

export const MOCK_OPTIMIZATIONS = [
  {
    title: 'Implementasi Caching Layer untuk Optimasi Performa',
    description: 'Requirement performa saat ini hanya fokus pada database optimization. Disarankan menambahkan Redis/Memcached sebagai caching layer untuk data statis dan session management. Ini akan mengurangi beban database hingga 60% dan mempercepat response time secara signifikan.',
    category: 'best_practice',
    priority: 'high',
    impact: 'Mengurangi response time dari 500ms ke <200ms, menghemat biaya database hingga 40%',
  },
  {
    title: 'Ambiguitas pada Definisi "Concurrent Users"',
    description: 'Requirement "10,000 concurrent users" tidak mendefinisikan apakah ini concurrent active sessions atau concurrent requests. Sebaiknya klarifikasi metrik performa menggunakan standar industri: TPS (transactions per second) dan Response Time Percentile (P95/P99).',
    category: 'ambiguous_spec',
    priority: 'high',
    impact: 'Mencegah over-provisioning infrastruktur yang bisa menghemat biaya hingga 50%',
  },
  {
    title: 'Gap pada Non-Functional Requirements untuk Disaster Recovery',
    description: 'Tidak ada requirement untuk RTO (Recovery Time Objective) dan RPO (Recovery Point Objective). Dokumen BRD perlu menambahkan metrik DR untuk menilai kesiapan infrastruktur menghadapi bencana.',
    category: 'missing_requirement',
    priority: 'high',
    impact: 'Menjamin business continuity, mencegah potensi kerugian >$1M per jam downtime',
  },
  {
    title: 'Otomasi Testing sebagai Bagian dari CI/CD Pipeline',
    description: 'Requirement hanya fokus pada fungsionalitas tanpa menyebutkan testing strategy. Disarankan menambahkan automated testing (unit, integration, E2E) sebagai bagian dari definisi selesai (DoD) untuk setiap fitur.',
    category: 'best_practice',
    priority: 'medium',
    impact: 'Mengurangi defect rate hingga 80% dan mempercepat siklus rilis dari bulanan menjadi mingguan',
  },
  {
    title: 'Bottleneck pada Proses Review Manual Hasil AI',
    description: 'Requirement ekstraksi AI menyebutkan review manual diperlukan, tapi tidak mendefinisikan SLA review. Jika tim BA hanya memiliki 2 orang, ini akan menjadi bottleneck. Rekomendasi: tambahkan batch review dengan priority scoring.',
    category: 'process_bottleneck',
    priority: 'medium',
    impact: 'Mempercepat waktu review AI dari 3 hari menjadi 4 jam',
  },
  {
    title: 'Potensi Compliance Risk pada Data Residency',
    description: 'Requirement GDPR menyebutkan data pengguna Eropa harus di server EU, tapi tidak ada spesifikasi multi-region deployment. Disarankan arsitektur dengan regional isolation dan data replication policy yang jelas.',
    category: 'compliance_risk',
    priority: 'high',
    impact: 'Memenuhi GDPR compliance, menghindari potensi denda hingga 4% revenue global',
  },
];

export const MOCK_SOLUTIONS = [
  {
    feature_id: 'F-01',
    feature_name: 'User Authentication & RBAC',
    solution_type: 'architecture',
    recommendation: 'Implementasi Keycloak sebagai Identity and Access Management (IAM) solution yang mendukung SAML 2.0, OAuth 2.0, dan MFA secara native. Integrasi dengan existing LDAP via Fedora IDM Bridge. Gunakan Spring Security untuk RBAC enforcement di service layer dengan policy-based access control (PBAC) untuk fleksibilitas yang lebih baik.',
    tech_stack: ['Keycloak', 'Spring Security', 'LDAP', 'Docker', 'PostgreSQL'],
    complexity: 'high',
    estimated_effort: '6-8 sprint (3-4 minggu per sprint)',
  },
  {
    feature_id: 'F-02',
    feature_name: 'Real-time Document Collaboration',
    solution_type: 'microservice',
    recommendation: 'Gunakan Operational Transformation (OT) via ShareJS atau CRDT-based approach menggunakan Yjs untuk conflict resolution. WebSocket connection dikelola oleh Socket.IO dengan Redis adapter untuk horizontal scaling. Dokumen store menggunakan MongoDB untuk fleksibilitas schema, dengan S3 untuk binary attachments.',
    tech_stack: ['Yjs', 'Socket.IO', 'Redis', 'MongoDB', 'AWS S3'],
    complexity: 'high',
    estimated_effort: '8-10 sprint',
  },
  {
    feature_id: 'F-03',
    feature_name: 'AI-Powered Requirement Extraction',
    solution_type: 'api_design',
    recommendation: 'Design API Gateway pattern dengan queue-based architecture menggunakan RabbitMQ untuk async LLM processing. Gunakan OpenAI API dengan custom fine-tuned model untuk extraction task. Implementasikan circuit breaker pattern dengan retry mechanism untuk handling API failures. Cache hasil extraction di Redis dengan TTL 24 jam.',
    tech_stack: ['FastAPI', 'RabbitMQ', 'OpenAI API', 'Redis', 'Celery'],
    complexity: 'medium',
    estimated_effort: '4-6 sprint',
  },
  {
    feature_id: 'F-04',
    feature_name: 'Dashboard & Reporting Analytics',
    solution_type: 'data_model',
    recommendation: 'Implementasikan data warehouse menggunakan Star Schema dengan Kimball methodology. Gunakan Apache Superset untuk dashboard dan reporting layer dengan direct query ke data warehouse. Metabase untuk ad-hoc reporting. CDC (Change Data Capture) menggunakan Debezium untuk real-time data sync ke warehouse.',
    tech_stack: ['Apache Superset', 'PostgreSQL (OLAP)', 'Debezium', 'Kafka', 'Metabase'],
    complexity: 'medium',
    estimated_effort: '6-8 sprint',
  },
];

export const MOCK_RISKS = [
  {
    risk_event: 'Integrasi SSO dengan legacy system mengalami kegagalan karena protokol tidak kompatibel',
    impact: 'critical',
    likelihood: 'likely',
    mitigation_strategy: 'Lakukan compatibility assessment sebelum implementasi. Siapkan fallback authentication mechanism. Buat proof of concept (POC) terlebih dahulu.',
    deep_dive: 'Legacy system menggunakan SAML 1.0 yang sudah deprecated. Upgrade path: perlu middleware adapter atau modernisasi legacy authentication. Dampak ke timeline: potensi delay 2-4 sprint. Mitigation: parallel running dengan existing auth selama 1 bulan.',
  },
  {
    risk_event: 'Performa database menurun drastis saat 10,000 user concurrent akibat missing index dan N+1 query',
    impact: 'high',
    likelihood: 'possible',
    mitigation_strategy: 'Implementasikan database query monitoring dari awal. Lakukan load testing secara berkala. Gunakan database connection pooling dan query optimization tools.',
    deep_dive: 'Berdasarkan pengalaman proyek serupa, N+1 query problem adalah penyebab #1 performa issue. Rekomendasi: implementasikan GraphQL untuk menghindari over/under fetching, atau gunakan ORM dengan batch loading (DataLoader pattern).',
  },
  {
    risk_event: 'Akurasi AI extraction <70% menyebabkan manual review overload dan bottleneck',
    impact: 'high',
    likelihood: 'possible',
    mitigation_strategy: 'Buat training dataset spesifik untuk domain BRD. Implementasikan human-in-the-loop feedback loop untuk continuous model improvement. Tetapkan SLA review yang realistis.',
    deep_dive: 'LLM-based extraction memiliki performa lebih baik pada dokumen terstruktur dibanding free-form text. Rekomendasi: gunakan chunking strategy dengan overlap untuk konteks yang lebih baik. Pertimbangkan RAG (Retrieval-Augmented Generation) dengan vector database untuk accuracy improvement.',
  },
  {
    risk_event: 'Data migration dari sistem lama memakan waktu lebih lama karena data quality issues',
    impact: 'medium',
    likelihood: 'likely',
    mitigation_strategy: 'Lakukan data profiling dan quality assessment sebelum migration. Buat data cleansing pipeline. Milestone dengan phase-based migration untuk mengurangi risiko.',
    deep_dive: 'Data quality issues umum meliputi: duplicate records, inconsistent formatting, missing foreign keys, dan orphaned data. Rekomendasi: gunakan Great Expectations untuk data quality validation. Pertimbangkan ETL tool seperti Airbyte atau Fivetran.',
  },
  {
    risk_event: 'Tim pengembangan tidak familiar dengan tech stack baru (Yjs, CRDT) menyebabkan learning curve delay',
    impact: 'medium',
    likelihood: 'certain',
    mitigation_strategy: 'Alokasikan 2 sprint untuk tech spike dan POC sebelum development utama. Libatkan konsultan eksternal untuk knowledge transfer. Siapkan internal documentation dan runbook.',
    deep_dive: 'CRDT dan OT adalah konsep yang kompleks. Learning curve rata-rata 4-6 minggu untuk productive. Risiko: implementasi yang salah bisa menyebabkan data inconsistency yang sulit di-recover. Mitigation: gunakan library yang mature (Yjs) dan hindari custom implementation.',
  },
];

export const MOCK_ADVISORY = [
  {
    title: 'Adopsi Event-Driven Architecture untuk Scalability',
    description: 'Beralih dari monolithic ke event-driven architecture menggunakan Kafka atau RabbitMQ akan memudahkan scaling horizontal dan memungkinkan integrasi real-time yang lebih reliable.',
    category: 'architecture',
    priority: 'high',
    impact: 'Mendukung pertumbuhan transaksi hingga 10x tanpa perubahan arsitektur mayor.',
  },
  {
    title: 'Implementasi API-first Development Strategy',
    description: 'Dengan mengadopsi API-first design menggunakan OpenAPI/Swagger specification, tim frontend dan backend dapat bekerja secara paralel, mengurangi dependencies, dan mempercepat time-to-market.',
    category: 'best_practice',
    priority: 'high',
    impact: 'Mempercepat delivery time sebesar 30-40% melalui parallel development.',
  },
  {
    title: 'Gunakan Cloud-Native Services untuk Mengurangi Operational Overhead',
    description: 'Leverage managed services (AWS RDS, ElastiCache, MSK) dibanding self-hosted solution untuk mengurangi beban operasional tim DevOps dan meningkatkan availability SLA.',
    category: 'best_practice',
    priority: 'medium',
    impact: 'Mengurangi operational overhead hingga 60% dengan managed services.',
  },
  {
    title: 'Terapkan Shift-Left Security dengan DevSecOps Pipeline',
    description: 'Integrasikan security scanning (SAST, DAST, dependency check) ke dalam CI/CD pipeline sejak sprint pertama untuk mengidentifikasi dan memperbaiki vulnerability lebih awal.',
    category: 'best_practice',
    priority: 'high',
    impact: 'Mengurangi biaya perbaikan security issue hingga 90% (ditemukan lebih awal).',
  },
  {
    title: 'Investasi pada Observability Stack dari Awal',
    description: 'Implementasikan distributed tracing (OpenTelemetry), centralized logging (ELK/Loki), dan metrics monitoring (Prometheus/Grafana) sejak hari pertama development untuk memudahkan debugging dan performance optimization.',
    category: 'best_practice',
    priority: 'medium',
    impact: 'Mengurangi MTTR (Mean Time to Resolve) dari 4 jam menjadi 30 menit.',
  },
];
